In [1]:
from google.colab import files
uploaded=files.upload() 
#uploading data

Saving vending_machine_sales.csv to vending_machine_sales.csv

In [2]:
import pandas as pd
#importing data

df=pd.read_csv('vending_machine_sales.csv')

df

,Status,ID,Location,Machine,Product,Category,Transaction,TransDate,Type,RCoil,RPrice,RQty,MCoil,MPrice,MQty,LineTotal,TransTotal,Date
0,Processed,VJ300320611,Brunswick Sq Mall,BSQ Mall x1366 - ATT,Red Bull - Energy Drink - Sugar Free,Carbonated,14515778905,"Saturday, January 1, 2022",Credit,148,3.5,1,148,3.5,1,3.5,3.5,1/1/2022
1,Processed,VJ300320611,Brunswick Sq Mall,BSQ Mall x1366 - ATT,Red Bull - Energy Drink - Sugar Free,Carbonated,14516018629,"Saturday, January 1, 2022",Credit,148,3.5,1,148,3.5,1,3.5,5.0,1/1/2022
2,Processed,VJ300320611,Brunswick Sq Mall,BSQ Mall x1366 - ATT,Takis - Hot Chilli Pepper & Lime,Food,14516018629,"Saturday, January 1, 2022",Credit,123,1.5,1,123,1.5,1,1.5,5.0,1/1/2022
3,Processed,VJ300320611,Brunswick Sq Mall,BSQ Mall x1366 - ATT,Takis - Hot Chilli Pepper & Lime,Food,14516020373,"Saturday, January 1, 2022",Credit,123,1.5,1,123,1.5,1,1.5,1.5,1/1/2022
4,Processed,VJ300320611,Brunswick Sq Mall,BSQ Mall x1366 - ATT,Red Bull - Energy Drink - Sugar Free,Carbonated,14516021756,"Saturday, January 1, 2022",Credit,148,3.5,1,148,3.5,1,3.5,3.5,1/1/2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6440,Processed,VJ300320692,EB Public Library,EB Public Library x1380,Lindens - Chocolate Chippers,Food,15603201222,"Wednesday, August 31, 2022",Credit,122,2.0,1,122,2.0,1,2.0,6.0,8/31/2022
6441,Processed,VJ300320692,EB Public Library,EB Public Library x1380,Wonderful Pistachios - Variety,Food,15603201222,"Wednesday, August 31, 2022",Credit,131,2.0,1,131,2.0,1,2.0,6.0,8/31/2022
6442,Processed,VJ300320692,EB Public Library,EB Public Library x1380,Hungry Buddha - Chocolate Chip,Food,15603201222,"Wednesday, August 31, 2022",Credit,137,2.0,1,137,2.0,1,2.0,6.0,8/31/2022
6443,Processed,VJ300320609,GuttenPlans,GuttenPlans x1367,Snapple Tea - Lemon,Non Carbonated,15603853105,"Wednesday, August 31, 2022",Credit,145,2.5,1,145,2.5,1,2.5,2.5,8/31/2022
6444,Processed,VJ300320692,EB Public Library,EB Public Library x1380,Goldfish Baked - Cheddar,Food,15603921383,"Wednesday, August 31, 2022",Cash,125,1.5,1,125,1.5,1,1.5,1.5,8/31/2022

In [3]:
df=df.dropna()
df=df.dropna(axis=0)
# Reset index after drop
df=df.dropna().reset_index(drop=True)

In [4]:
print(pd.unique(df['ID']))
print(pd.unique(df['Location']))
print(pd.unique(df['Machine']))
print(pd.unique(df['Type']))
print(pd.unique(df['Category']))
#print(pd.unique(df['Product']))

['VJ300320611' 'VJ300205292' 'VJ300320686' 'VJ300320609' 'VJ300320692']
['Brunswick Sq Mall' 'Earle Asphalt' 'GuttenPlans' 'EB Public Library']
['BSQ Mall x1366 - ATT' 'BSQ Mall x1364 - Zales' 'Earle Asphalt x1371'
 'GuttenPlans x1367' 'EB Public Library x1380']
['Credit' 'Cash']
['Carbonated' 'Food' 'Non Carbonated' 'Water']

In [5]:
df1=df[(df.ID== "VJ300320609") & (df.Location=="GuttenPlans")]
p1=df1['Product'].value_counts(ascending=True)
placement_1=df1['RCoil'].value_counts()
placement_11=placement_1.head()

In [6]:
#RCOIL VENDING #1 -- need to fix

for i in range(5):
  if i == 0:
    d11=placement_11.index[i]
    df11=df1[(df.RCoil==d11)]
    df111=df11['Product'].value_counts(ascending=True)
    rows111 = len(df111.axes[0])
    df1111 = pd.DataFrame(columns = ['Product', 'Number-of-Product-Sold', 'RCoil'])
    for i in range(rows111):
        x=df111.index[i]
        y=df111.iloc[i]
        df1111.loc[i] = [x] + [int(y)] + [d11]
  if i == 1:
    d12=placement_11.index[i]
    df12=df1[(df.RCoil==d12)]
    df122=df12['Product'].value_counts(ascending=True)
    rows122 = len(df122.axes[0])
    df1221 = pd.DataFrame(columns = ['Product', 'Number-of-Product-Sold', 'RCoil'])
    for i in range(rows122):
      x=df122.index[i]
      y=df122.iloc[i]
      df1221.loc[i] = [x] + [int(y)] + [d12]
  if i == 2:
    d13=placement_11.index[i]
    df13=df1[(df.RCoil==d13)]
    df133=df13['Product'].value_counts(ascending=True)
    rows133 = len(df133.axes[0])
    df1331 = pd.DataFrame(columns = ['Product', 'Number-of-Product-Sold', 'RCoil'])
    for i in range(rows133):
      x=df133.index[i]
      y=df133.iloc[i]
      df1331.loc[i] = [x] + [int(y)] + [d13]
  if i == 3:
    d14=placement_11.index[i]
    df14=df1[(df.RCoil==d14)]
    df144=df14['Product'].value_counts(ascending=True)
    rows144 = len(df144.axes[0])
    df1441 = pd.DataFrame(columns = ['Product', 'Number-of-Product-Sold', 'RCoil'])
    for i in range(rows144):
      x=df144.index[i]
      y=df144.iloc[i]
      df1441.loc[i] = [x] + [int(y)] + [d14]
  if i == 4:
    d15=placement_11.index[i]
    df15=df1[(df.RCoil==d15)]
    df155=df15['Product'].value_counts(ascending=True)
    rows155 = len(df155.axes[0])
    df1551 = pd.DataFrame(columns = ['Product', 'Number-of-Product-Sold', 'RCoil'])
    for i in range(rows155):
      x=df155.index[i]
      y=df155.iloc[i]
      df1551.loc[i] = [x] + [int(y)] + [d15]

frames_1 = [df1111, df1221, df1331, df1441, df1551]
result_1 = pd.concat(frames_1, keys=["Highest Sold/RCoil Vending Machine #1", "y", "z", "v", "Lowest Sold/RCoil Vending Machine #1"])

result_1

<ipython-input-6-4e7bfe7197ce>:6: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df11=df1[(df.RCoil==d11)]
<ipython-input-6-4e7bfe7197ce>:16: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df12=df1[(df.RCoil==d12)]
<ipython-input-6-4e7bfe7197ce>:26: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df13=df1[(df.RCoil==d13)]
<ipython-input-6-4e7bfe7197ce>:36: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df14=df1[(df.RCoil==d14)]
<ipython-input-6-4e7bfe7197ce>:46: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df15=df1[(df.RCoil==d15)]

                                                                   Product  \
Highest Sold/RCoil Vending Machine #1 0  Spindrift - Sparkling Water  Lime
                                      1              Sunkist Soda - Orange
y                                     0                Coca Cola - Regular
                                      1             Coca Cola - Zero Sugar
z                                     0                Coca Cola - Regular
                                      1             Coca Cola - Zero Sugar
v                                     0            Monster Energy Original
Lowest Sold/RCoil Vending Machine #1  0            Monster Energy Original

                                        Number-of-Product-Sold RCoil
Highest Sold/RCoil Vending Machine #1 0                      3   140
                                      1                    217   140
y                                     0                     78   141
                                      1                    141   141
z                                     0                     67   142
                                      1                    139   142
v                                     0                    161   146
Lowest Sold/RCoil Vending Machine #1  0                    146   144

In [7]:
df2=df[(df.ID== "VJ300320692") & (df.Location=="EB Public Library")]
p2=df2['Product'].value_counts(ascending=True)

In [8]:
#RCOIL VENDING #2
placement_2=df2['RCoil'].value_counts()
placement_22=placement_2.head()
for i in range(5):
  if i == 0:
    d21=placement_22.index[i]
    df21=df2[(df.RCoil==d21)]
    df211=df21['Product'].value_counts(ascending=True)
    rows211 = len(df211.axes[0])
    df2112 = pd.DataFrame(columns = ['Product', 'Number-of-Product-Sold', 'RCoil'])
    for i in range(rows211):
        x=df211.index[i]
        y=df211.iloc[i]
        df2112.loc[i] = [x] + [int(y)] + [d21]
  if i == 1:
    d22=placement_22.index[i]
    df22=df2[(df.RCoil==d22)]
    df222=df22['Product'].value_counts(ascending=True)
    rows222 = len(df222.axes[0])
    df2222 = pd.DataFrame(columns = ['Product', 'Number-of-Product-Sold', 'RCoil'])
    for i in range(rows222):
      x=df222.index[i]
      y=df222.iloc[i]
      df2222.loc[i] = [x] + [int(y)] + [d22]
  if i == 2:
    d23=placement_22.index[i]
    df23=df2[(df.RCoil==d23)]
    df233=df23['Product'].value_counts(ascending=True)
    rows233 = len(df233.axes[0])
    df2332 = pd.DataFrame(columns = ['Product', 'Number-of-Product-Sold', 'RCoil'])
    for i in range(rows233):
      x=df233.index[i]
      y=df233.iloc[i]
      df2332.loc[i] = [x] + [int(y)] + [d23]
  if i == 3:
    d24=placement_22.index[i]
    df24=df2[(df.RCoil==d24)]
    df244=df24['Product'].value_counts(ascending=True)
    rows244 = len(df244.axes[0])
    df2442 = pd.DataFrame(columns = ['Product', 'Number-of-Product-Sold', 'RCoil'])
    for i in range(rows244):
      x=df244.index[i]
      y=df244.iloc[i]
      df2442.loc[i] = [x] + [int(y)] + [d24]
  if i == 4:
    d25=placement_22.index[i]
    df25=df2[(df.RCoil==d25)]
    df255=df25['Product'].value_counts(ascending=True)
    rows255 = len(df255.axes[0])
    df2552 = pd.DataFrame(columns = ['Product', 'Number-of-Product-Sold', 'RCoil'])
    for i in range(rows255):
      x=df255.index[i]
      y=df255.iloc[i]
      df2552.loc[i] = [x] + [int(y)] + [d25]

frames_2 = [df2112, df2222, df2332, df2442, df2552]
result_2 = pd.concat(frames_2, keys=["Highest Sold/RCoil Vending Machine #2", "y", "z", "v", "Lowest Sold/RCoil Vending Machine #2"])

result_2

<ipython-input-8-8d1f5c75b5e9>:7: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df21=df2[(df.RCoil==d21)]
<ipython-input-8-8d1f5c75b5e9>:17: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df22=df2[(df.RCoil==d22)]
<ipython-input-8-8d1f5c75b5e9>:27: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df23=df2[(df.RCoil==d23)]
<ipython-input-8-8d1f5c75b5e9>:37: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df24=df2[(df.RCoil==d24)]
<ipython-input-8-8d1f5c75b5e9>:47: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df25=df2[(df.RCoil==d25)]

                                                                               Product  \
Highest Sold/RCoil Vending Machine #2 0          S. Pellegrino Sparkling Mineral Water
                                      1                           Poland Springs Water
y                                     0              Spindrift - Sparkling Water  Lime
                                      1                         Coca Cola - Zero Sugar
z                                     0  Miss Vickie's Potato Chip - Sea Salt Original
                                      1           Miss Vickie's Potato Chip - Jalapeno
                                      2          SunChips Multigrain - Harvest Cheddar
                                      3  Miss Vickie's Potato Chip - Sea Salt & Vinega
                                      4                    SunChips Multigrain - Salsa
                                      5                    Pop Corners - White Cheddar
v                                     0  Miss Vickie's Potato Chip - Sea Salt & Vinega
                                      1             Good Health Veggie Stix - Sea Salt
                                      2                      Pop Corners - Kettle Corn
                                      3          SunChips Multigrain - Harvest Cheddar
Lowest Sold/RCoil Vending Machine #2  0                          TruBar - Cookie Dough
                                      1       Kinder - Bueno - Crispy Creamy Chocolate
                                      2                Belvita Snack Packs - Blueberry
                                      3                        Oreo Single Server 6 ct
                                      4                          KitKat - Crisp Wafers

                                        Number-of-Product-Sold RCoil
Highest Sold/RCoil Vending Machine #2 0                     22   144
                                      1                    127   144
y                                     0                      6   142
                                      1                    140   142
z                                     0                      4   113
                                      1                      6   113
                                      2                      7   113
                                      3                     10   113
                                      4                     25   113
                                      5                     28   113
v                                     0                      6   110
                                      1                     11   110
                                      2                     29   110
                                      3                     30   110
Lowest Sold/RCoil Vending Machine #2  0                      4   138
                                      1                     14   138
                                      2                     15   138
                                      3                     19   138
                                      4                     24   138

In [9]:
df3=df[(df.ID== "VJ300320686") & (df.Location=="Earle Asphalt")]
p3=df3['Product'].value_counts(ascending=True)
placement_3=df3['RCoil'].value_counts()
placement_33=placement_3.head()

In [10]:
#RCOIL VENDING #3
placement_3=df3['RCoil'].value_counts()
placement_33=placement_3.head()
for i in range(5):
  if i == 0:
    d31=placement_33.index[i]
    df31=df3[(df.RCoil==d31)]
    df311=df31['Product'].value_counts(ascending=True)
    rows311 = len(df311.axes[0])
    df3113 = pd.DataFrame(columns = ['Product', 'Number-of-Product-Sold', 'RCoil'])
    for i in range(rows311):
        x=df311.index[i]
        y=df311.iloc[i]
        df3113.loc[i] = [x] + [int(y)] + [d31]
  if i == 1:
    d32=placement_33.index[i]
    df32=df3[(df.RCoil==d32)]
    df322=df32['Product'].value_counts(ascending=True)
    rows322 = len(df322.axes[0])
    df3223 = pd.DataFrame(columns = ['Product', 'Number-of-Product-Sold', 'RCoil'])
    for i in range(rows322):
      x=df322.index[i]
      y=df322.iloc[i]
      df3223.loc[i] = [x] + [int(y)] + [d32]
  if i == 2:
    d33=placement_33.index[i]
    df33=df3[(df.RCoil==d33)]
    df333=df33['Product'].value_counts(ascending=True)
    rows333 = len(df333.axes[0])
    df3333 = pd.DataFrame(columns = ['Product', 'Number-of-Product-Sold', 'RCoil'])
    for i in range(rows333):
      x=df333.index[i]
      y=df333.iloc[i]
      df3333.loc[i] = [x] + [int(y)] + [d33]
  if i == 3:
    d34=placement_33.index[i]
    df34=df3[(df.RCoil==d34)]
    df344=df34['Product'].value_counts(ascending=True)
    rows344 = len(df344.axes[0])
    df3443 = pd.DataFrame(columns = ['Product', 'Number-of-Product-Sold', 'RCoil'])
    for i in range(rows344):
      x=df344.index[i]
      y=df344.iloc[i]
      df3443.loc[i] = [x] + [int(y)] + [d34]
  if i == 4:
    d35=placement_33.index[i]
    df35=df3[(df.RCoil==d35)]
    df355=df35['Product'].value_counts(ascending=True)
    rows355 = len(df355.axes[0])
    df3553 = pd.DataFrame(columns = ['Product', 'Number-of-Product-Sold', 'RCoil'])
    for i in range(rows355):
      x=df355.index[i]
      y=df355.iloc[i]
      df3553.loc[i] = [x] + [int(y)] + [d35]

frames_3 = [df3113, df3223, df3333, df3443, df3553]
result_3 = pd.concat(frames_3, keys=["Highest Sold/RCoil Vending Machine #3", "y", "z", "v", "Lowest Sold/RCoil Vending Machine #3"])

result_3

<ipython-input-10-ed0b40f6c11f>:7: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df31=df3[(df.RCoil==d31)]
<ipython-input-10-ed0b40f6c11f>:27: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df33=df3[(df.RCoil==d33)]
<ipython-input-10-ed0b40f6c11f>:17: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df32=df3[(df.RCoil==d32)]
<ipython-input-10-ed0b40f6c11f>:37: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df34=df3[(df.RCoil==d34)]
<ipython-input-10-ed0b40f6c11f>:47: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df35=df3[(df.RCoil==d35)]

                                                                               Product  \
Highest Sold/RCoil Vending Machine #3 0                  Keto Krisp - Almond/Chocolate
                                      1      Keto Bar - Creamy Peanut Butter Chocolate
                                      2                 Wonderful Pistachios - Variety
y                                     0                 Wonderful Pistachios - Variety
                                      1  Robert Irvine's - Fit Crunch -  Chocolate Pea
z                                     0                      Pop Corners - Spicy Queso
                                      1           Miss Vickie's Potato Chip - Jalapeno
                                      2                    Pop Corners - White Cheddar
                                      3          SunChips Multigrain - Harvest Cheddar
                                      4                    SunChips Multigrain - Salsa
                                      5     Miss Vickie's Potato Chip - Smokehouse BBQ
v                                     0          SunChips Multigrain - Harvest Cheddar
                                      1  Miss Vickie's Potato Chip - Sea Salt & Vinega
                                      2  Miss Vickie's Potato Chip - Lime & Cracked Pe
                                      3                    SunChips Multigrain - Salsa
Lowest Sold/RCoil Vending Machine #3  0  Miss Vickie's Potato Chip - Sea Salt & Vinega
                                      1                      Pop Corners - Kettle Corn
                                      2             Good Health Veggie Stix - Sea Salt
                                      3           Miss Vickie's Potato Chip - Jalapeno

                                        Number-of-Product-Sold RCoil
Highest Sold/RCoil Vending Machine #3 0                      8   138
                                      1                     10   138
                                      2                     68   138
y                                     0                      7   132
                                      1                     63   132
z                                     0                      4   111
                                      1                      5   111
                                      2                      5   111
                                      3                      7   111
                                      4                      7   111
                                      5                     22   111
v                                     0                      7   110
                                      1                     10   110
                                      2                     14   110
                                      3                     15   110
Lowest Sold/RCoil Vending Machine #3  0                      3   113
                                      1                      9   113
                                      2                     13   113
                                      3                     21   113

In [11]:
df4=df[(df.ID== "VJ300205292") & (df.Location=="Brunswick Sq Mall")]
p4=df4['Product'].value_counts(ascending=True)

In [12]:
#RCOIL VENDING #4
placement_4=df4['RCoil'].value_counts()
placement_44=placement_4.head()
for i in range(5):
  if i == 0:
    d41=placement_44.index[i]
    df41=df4[(df.RCoil==d41)]
    df411=df41['Product'].value_counts(ascending=True)
    rows411 = len(df411.axes[0])
    df4114 = pd.DataFrame(columns = ['Product', 'Number-of-Product-Sold', 'RCoil'])
    for i in range(rows411):
        x=df411.index[i]
        y=df411.iloc[i]
        df4114.loc[i] = [x] + [int(y)] + [d41]
  if i == 1:
    d42=placement_44.index[i]
    df42=df4[(df.RCoil==d42)]
    df422=df42['Product'].value_counts(ascending=True)
    rows422 = len(df422.axes[0])
    df4224 = pd.DataFrame(columns = ['Product', 'Number-of-Product-Sold', 'RCoil'])
    for i in range(rows422):
      x=df422.index[i]
      y=df422.iloc[i]
      df4224.loc[i] = [x] + [int(y)] + [d42]
  if i == 2:
    d43=placement_44.index[i]
    df43=df4[(df.RCoil==d43)]
    df433=df43['Product'].value_counts(ascending=True)
    rows433 = len(df433.axes[0])
    df4334 = pd.DataFrame(columns = ['Product', 'Number-of-Product-Sold', 'RCoil'])
    for i in range(rows433):
      x=df433.index[i]
      y=df433.iloc[i]
      df4334.loc[i] = [x] + [int(y)] + [d43]
  if i == 3:
    d44=placement_44.index[i]
    df44=df4[(df.RCoil==d44)]
    df444=df44['Product'].value_counts(ascending=True)
    rows444 = len(df444.axes[0])
    df4444 = pd.DataFrame(columns = ['Product', 'Number-of-Product-Sold', 'RCoil'])
    for i in range(rows444):
      x=df444.index[i]
      y=df444.iloc[i]
      df4444.loc[i] = [x] + [int(y)] + [d44]
  if i == 4:
    d45=placement_44.index[i]
    df45=df4[(df.RCoil==d45)]
    df455=df45['Product'].value_counts(ascending=True)
    rows455 = len(df455.axes[0])
    df4554 = pd.DataFrame(columns = ['Product', 'Number-of-Product-Sold', 'RCoil'])
    for i in range(rows455):
      x=df455.index[i]
      y=df455.iloc[i]
      df4554.loc[i] = [x] + [int(y)] + [d45]

frames_4 = [df4114, df4224, df4334, df4444, df4554]
result_4 = pd.concat(frames_4, keys=["Highest Sold/RCoil Vending Machine #4", "y", "z", "v", "Lowest Sold/RCoil Vending Machine #4"])

result_4

<ipython-input-12-aa46310d65cd>:7: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df41=df4[(df.RCoil==d41)]
<ipython-input-12-aa46310d65cd>:17: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df42=df4[(df.RCoil==d42)]
<ipython-input-12-aa46310d65cd>:27: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df43=df4[(df.RCoil==d43)]
<ipython-input-12-aa46310d65cd>:37: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df44=df4[(df.RCoil==d44)]
<ipython-input-12-aa46310d65cd>:47: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df45=df4[(df.RCoil==d45)]

                                                                            Product  \
Highest Sold/RCoil Vending Machine #4 0                        Poland Springs Water
y                                     0  Spindrift - Sparkling Water Raspberry Lime
                                      1                      Coca Cola - Zero Sugar
z                                     0               Bai Antioxidant - Brasilia BB
                                      1         Bai Antioxidant - Zambia Bingcherry
                                      2                     Monster Energy Original
v                                     0                Snapple Diet Tea - Peach Tea
Lowest Sold/RCoil Vending Machine #4  0       SunChips Multigrain - Harvest Cheddar
                                      1          Good Health Veggie Stix - Sea Salt
                                      2                 SunChips Multigrain - Salsa
                                      3                       Lays Baked - Original
                                      4                   Pop Corners - Spicy Queso
                                      5              SunChips Multigrain - Original

                                        Number-of-Product-Sold RCoil
Highest Sold/RCoil Vending Machine #4 0                    143   144
y                                     0                      2   140
                                      1                     61   140
z                                     0                      4   146
                                      1                      8   146
                                      2                     42   146
v                                     0                     40   143
Lowest Sold/RCoil Vending Machine #4  0                      1   111
                                      1                      5   111
                                      2                      6   111
                                      3                      7   111
                                      4                     10   111
                                      5                     10   111

In [13]:
df5=df[(df.ID== "VJ300320611") & (df.Location=="Brunswick Sq Mall")]
p5=df5['Product'].value_counts(ascending=True)

In [14]:
#RCOIL VENDING #5
placement_5=df5['RCoil'].value_counts()
placement_55=placement_5.head()
for i in range(5):
  if i == 0:
    d51=placement_55.index[i]
    df51=df5[(df.RCoil==d51)]
    df511=df51['Product'].value_counts(ascending=True)
    rows511 = len(df511.axes[0])
    df5115 = pd.DataFrame(columns = ['Product', 'Number-of-Product-Sold', 'RCoil'])
    for i in range(rows511):
        x=df511.index[i]
        y=df511.iloc[i]
        df5115.loc[i] = [x] + [int(y)] + [d51]
  if i == 1:
    d52=placement_55.index[i]
    df52=df5[(df.RCoil==d52)]
    df522=df52['Product'].value_counts(ascending=True)
    rows522 = len(df522.axes[0])
    df5225 = pd.DataFrame(columns = ['Product', 'Number-of-Product-Sold', 'RCoil'])
    for i in range(rows522):
      x=df522.index[i]
      y=df522.iloc[i]
      df5225.loc[i] = [x] + [int(y)] + [d52]
  if i == 2:
    d53=placement_55.index[i]
    df53=df5[(df.RCoil==d53)]
    df533=df53['Product'].value_counts(ascending=True)
    rows533 = len(df533.axes[0])
    df5335 = pd.DataFrame(columns = ['Product', 'Number-of-Product-Sold', 'RCoil'])
    for i in range(rows533):
      x=df533.index[i]
      y=df533.iloc[i]
      df5335.loc[i] = [x] + [int(y)] + [d53]
  if i == 3:
    d54=placement_55.index[i]
    df54=df5[(df.RCoil==d54)]
    df544=df54['Product'].value_counts(ascending=True)
    rows544 = len(df544.axes[0])
    df5445 = pd.DataFrame(columns = ['Product', 'Number-of-Product-Sold', 'RCoil'])
    for i in range(rows544):
      x=df544.index[i]
      y=df544.iloc[i]
      df5445.loc[i] = [x] + [int(y)] + [d54]
  if i == 4:
    d55=placement_55.index[i]
    df55=df5[(df.RCoil==d55)]
    df555=df55['Product'].value_counts(ascending=True)
    rows555 = len(df555.axes[0])
    df5555 = pd.DataFrame(columns = ['Product', 'Number-of-Product-Sold', 'RCoil'])
    for i in range(rows555):
      x=df555.index[i]
      y=df555.iloc[i]
      df5555.loc[i] = [x] + [int(y)] + [d55]
    #df5555['Product'].sum()

frames_5 = [df5115, df5225, df5335, df5445, df5555]
result_5 = pd.concat(frames_5, keys=["Highest Sold/RCoil Vending Machine #5", "y", "z", "v", "Lowest Sold/RCoil Vending Machine #5"])

result_5

<ipython-input-14-49958b352ef9>:7: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df51=df5[(df.RCoil==d51)]
<ipython-input-14-49958b352ef9>:17: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df52=df5[(df.RCoil==d52)]
<ipython-input-14-49958b352ef9>:37: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df54=df5[(df.RCoil==d54)]
<ipython-input-14-49958b352ef9>:27: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df53=df5[(df.RCoil==d53)]
<ipython-input-14-49958b352ef9>:47: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df55=df5[(df.RCoil==d55)]

                                                                          Product  \
Highest Sold/RCoil Vending Machine #5 0                      Poland Springs Water
                                      1     S. Pellegrino Sparkling Mineral Water
y                                     0      BodyArmor LYTE - Strawberry Lemonade
                                      1                   Snapple Tea - Raspberry
                                      2                       Snapple Tea - Lemon
                                      3              Snapple Diet Tea - Raspberry
z                                     0  Starbucks Refresher - Real Coconut Water
                                      1      Red Bull - Energy Drink - Sugar Free
                                      2                       Red Bull - Original
v                                     0                   Monster Energy Original
Lowest Sold/RCoil Vending Machine #5  0                   Snapple Tea - Raspberry
                                      1          Bai Lemonade - Burundi Blueberry
                                      2  Bai Antioxidant - Kupang strawberry kiwi
                                      3         Bai Antioxidant - Molokai Coconut

                                        Number-of-Product-Sold RCoil
Highest Sold/RCoil Vending Machine #5 0                     20   143
                                      1                     44   143
y                                     0                      5   145
                                      1                      8   145
                                      2                     14   145
                                      3                     19   145
z                                     0                      8   148
                                      1                     13   148
                                      2                     13   148
v                                     0                     34   146
Lowest Sold/RCoil Vending Machine #5  0                      6   144
                                      1                      7   144
                                      2                      8   144
                                      3                     12   144